name: Spellchecker CLI

on:
  pull_request:
    branches: [develop]
    types: ['opened', 'reopened', 'ready_for_review']

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - uses: actions/checkout@v3
      - uses: tbroadley/spellchecker-cli-action@v1
        with:
          files: "**/*.tsx **/*.ts"
          dictionaries: "dictionary.txt"
          quiet: true
          

